import { useMemo, useState } from 'react'
import TabShell, { TabEmpty, TabError, TabLoading } from '../../components/TabShell'
import { usePeakForecast, usePredictionLog } from './hooks'
import { HORIZON_OPTS, filterPeaksByHorizon, relTime } from './calculations'
import PeriodExplainer from './components/PeriodExplainer'
import RunningBoard from './components/RunningBoard'
import PeakCard from './components/PeakCard'
import PeakTable from './components/PeakTable'
import AccuracyPanel from './components/AccuracyPanel'
import TrailingAccuracyPanel from './components/TrailingAccuracyPanel'

// Peak Forecast tab — the ICI-consumer 5CP view. Renders the pipeline's
// forecast (public/peak-forecast/forecast.json): the current base period's
// running top-5 board, and up to 5 upcoming hours that would crack it (the
// curtailment targets). See pipeline/src/forecast.js for the model + shape.
export default function PeakForecastTab() {
  const [horizon, setHorizon] = useState(14)
  const [view, setView] = useState('cards')

  // `bustCache` on a manual refresh re-reads the currently-published
  // forecast.json (bypassing CDN/browser cache). It reloads deployed data — it
  // does not regenerate the forecast; that happens in the pipeline.
  const { data, error, loading, refreshing, refresh } = usePeakForecast()

  // The prospective prediction log drives the live trailing-accuracy panel. It
  // is deliberately NOT gated into the tab's loading/error path: a missing or
  // young log is a normal "not accrued yet" state (fetchPredictionLog never
  // rejects), so the panel simply renders once logData is present.
  const { data: logData } = usePredictionLog()

  const visiblePeaks = useMemo(
    () => (data ? filterPeaksByHorizon(data.predictedPeaks, horizon) : []),
    [data, horizon],
  )

  if (loading) {
    return <TabLoading>Loading forecast…</TabLoading>
  }
  if (error || !data) {
    return <TabError>{error ?? 'Forecast unavailable.'}</TabError>
  }

  const rel = relTime(data.generatedAt)
  return (
    <TabShell
      className="mx-auto w-full max-w-5xl"
      title={
        <h2 className="text-lg font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
          5CP Peak Forecast
          <span className="ml-2 align-middle text-xs font-medium text-zinc-500">base period {data.basePeriod.label}</span>
        </h2>
      }
      subtitle="When to curtail to stay out of this year's five coincident peaks."
      actions={
        <div className="flex flex-col items-end gap-1 text-right">
          <div className="flex items-center gap-2">
            {data.sample ? (
              <span className="inline-flex items-center gap-1.5 rounded-full bg-amber-500/15 px-2.5 py-1 text-[11px] font-semibold text-amber-700 dark:text-amber-300">
                <span className="h-1.5 w-1.5 rounded-full bg-amber-500" />
                Sample data
              </span>
            ) : (
              <span
                className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/15 px-2.5 py-1 text-[11px] font-semibold text-emerald-700 dark:text-emerald-300"
                title="Rendering a real pipeline run (not the checked-in sample)."
              >
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                Live
              </span>
            )}
            <button
              onClick={() => refresh({ bustCache: true })}
              disabled={refreshing}
              title="Reload the latest published forecast. New forecasts are generated by the pipeline (npm run export:dashboard) and deployed with the site."
              aria-label="Refresh forecast data"
              className="inline-flex items-center gap-1.5 rounded-md border border-zinc-300 bg-white px-2.5 py-1 text-[11px] font-medium text-zinc-600 hover:bg-zinc-100 hover:text-zinc-800 disabled:cursor-not-allowed disabled:opacity-60 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700 dark:hover:text-zinc-100"
            >
              <svg
                className={`h-3.5 w-3.5 ${refreshing ? 'animate-spin' : ''}`}
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M21 12a9 9 0 1 1-2.64-6.36" />
                <path d="M21 3v6h-6" />
              </svg>
              {refreshing ? 'Refreshing…' : 'Refresh'}
            </button>
          </div>
          <span className="text-[11px] text-zinc-500">
            generated {rel ?? '—'} · data through {data.datasetThrough}
          </span>
        </div>
      }
    >
      {data.staleNote && (
        <div className="rounded-lg border border-amber-500/40 bg-amber-500/5 px-3 py-2 text-xs text-amber-700 dark:text-amber-300">
          {data.staleNote}
        </div>
      )}

      <PeriodExplainer basePeriod={data.basePeriod} billingPeriod={data.billingPeriod} />
      <RunningBoard running5CP={data.running5CP} threshold={data.threshold} />

      {/* controls */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-zinc-500">Horizon</span>
          <div className="flex overflow-hidden rounded-md border border-zinc-300 dark:border-zinc-700">
            {HORIZON_OPTS.map((h) => (
              <button
                key={h}
                onClick={() => setHorizon(h)}
                className={`px-3 py-1.5 text-xs font-medium ${
                  horizon === h
                    ? 'bg-sky-500/15 text-sky-700 dark:bg-sky-500/20 dark:text-sky-300'
                    : 'bg-white text-zinc-500 hover:text-zinc-800 dark:bg-zinc-800 dark:text-zinc-400 dark:hover:text-zinc-200'
                }`}
              >
                {h} days
              </button>
            ))}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-zinc-500">View</span>
          <div className="flex overflow-hidden rounded-md border border-zinc-300 dark:border-zinc-700">
            {[['cards', 'Cards'], ['table', 'Table']].map(([id, label]) => (
              <button
                key={id}
                onClick={() => setView(id)}
                className={`px-3 py-1.5 text-xs font-medium ${
                  view === id
                    ? 'bg-sky-500/15 text-sky-700 dark:bg-sky-500/20 dark:text-sky-300'
                    : 'bg-white text-zinc-500 hover:text-zinc-800 dark:bg-zinc-800 dark:text-zinc-400 dark:hover:text-zinc-200'
                }`}
              >
                {label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* predicted peaks */}
      {visiblePeaks.length === 0 ? (
        <TabEmpty>No predicted peaks within {horizon} days that approach the current top-5.</TabEmpty>
      ) : view === 'cards' ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {visiblePeaks.map((p) => <PeakCard key={p.date} p={p} />)}
        </div>
      ) : (
        <PeakTable peaks={visiblePeaks} />
      )}

      <AccuracyPanel
        accuracyByLead={data.accuracyByLead}
        accuracyBaseline={data.accuracyBaseline}
        horizons={data.horizons}
      />

      {logData && (
        <TrailingAccuracyPanel predictions={logData.predictions} updatedAt={logData.updatedAt} />
      )}

      <p className="text-[11px] leading-relaxed text-zinc-500">
        Forecast from the peak-prediction pipeline (demand + weather OLS model), exported to
        <code className="mx-1 rounded bg-zinc-100 px-1 dark:bg-zinc-800">public/peak-forecast/forecast.json</code>.
        Weather input is ECCC's forecast within ~7 days, climatology beyond it. Not affiliated with the IESO.
      </p>
    </TabShell>
  )
}
